### PR TITLE
(fix) Validation situations where Expo returns a 200 with an error

### PR DESCRIPTION
**Pull request by 0duaht**
Fixes failures with data validation cos the Hash is being converted to an array

### CODE REVIEW

**Review by aroeczek-old — CHANGES_REQUESTED** [review]
We spotted similar errors in our app, it looks like you forgot to deal with other occurrences of response.fetch('errors').first in lines 110, 118

**Comment by 0duaht** [comment]
@aroeczek does https://github.com/expo/expo-server-sdk-ruby/pull/14/commits/688f1bb4b142d2e211381854b2af4d523dabcc16 also work with your use-case?

**Comment by aroeczek** [comment]
@0duaht Look like everything is ok with PR code, I didn't spot mentioned commit.

**Comment by kevinzhangftw** [comment]
yep, just test it this and it works. Can somebody from expo merge this request?

**Comment by coffenbacher** [comment]
I don't understand why the first element is returned every time, it seems to me like it should always be an array rather than always a single value 🤔 

https://github.com/expo/expo-server-sdk-ruby/issues/18

**Comment by courtsimas** [comment]
any movement on this?

**Comment by ghost** [comment]
Closed in favor of https://github.com/expo-community/expo-server-sdk-ruby/pull/29

**Pull request closed without merging**
