### PR TITLE
Fix UnknownError message

### PR DESCRIPTION
**Pull request by aki77**
I'm having trouble finding more information on UnknownError.
#33

### CODE REVIEW

**Comment by foolem** [comment]
We need this one. +1

**Comment by kamalpandey** [comment]
+1

**Comment by wilco** [comment]
+1

**Comment by 026binit** [comment]
+1

**Comment by vandemberg** [comment]
+2

**Comment by sanak** [comment]
+1

**Comment by akichim21** [comment]
+1

**Comment by FabioMussi** [comment]
+ 1

**Comment by mountriv99** [comment]
+1

**Comment by kevgrig** [comment]
@pablonahuelgomez Hi Pablo, can you please merge this? I have been running with this PR on a fork in production for months and it works and provides important exception details. It [helped me](https://github.com/expo-community/expo-server-sdk-ruby/issues/39) find out that the Expo server was responding with an HTTP 504 and to add exponential backoff.

**Comment by kevgrig** [comment]
@pablonahuelgomez Also, this is not just for debugging; the exception contents are needed to check for HTTP 429 and HTTP 5XX status to perform [exponential retry](https://docs.expo.dev/push-notifications/sending-notifications/#retry-on-failure) as [recommended by Expo development](https://github.com/expo/expo/issues/6486#issuecomment-954284679).

**Comment by kevgrig** [comment]
@pablonahuelgomez Thanks for the merge! Can you please also publish a new version of the gem?

Until then, the Gemfile workaround is:

```
gem 'exponent-server-sdk', git: "https://github.com/expo-community/expo-server-sdk-ruby.git", branch: "master"
```

**Comment by alistairholt** [comment]
Who is actually maintaining this gem? @pablonahuelgomez why was there no release on Rubygems after the merge?

If this gem is being abandoned for the community to maintain **please** make someone else a maintainer so we can address the issues with this project.

**Comment by oriolblanc** [comment]
Any update on this?

**Pull request merged**
